include: package:pedantic_mono/analysis_options.yaml
analyzer:
  errors:
    missing_required_param: error
    missing_return: warning
    sdk_version_async_exported_from_core: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/l10n/*.dart